/**
 * @fileoverview gRPC-Web generated client stub for chat_package
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat_pb from './chat_pb'; // proto import: "chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chat_package.ChatService/SendMessage',
    grpcWeb.MethodType.UNARY,
    chat_pb.Message,
    chat_pb.SendMessageResponse,
    (request: chat_pb.Message) => {
      return request.serializeBinary();
    },
    chat_pb.SendMessageResponse.deserializeBinary
  );

  sendMessage(
    request: chat_pb.Message,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.SendMessageResponse>;

  sendMessage(
    request: chat_pb.Message,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.SendMessageResponse) => void): grpcWeb.ClientReadableStream<chat_pb.SendMessageResponse>;

  sendMessage(
    request: chat_pb.Message,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.SendMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat_package.ChatService/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat_package.ChatService/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorGetHistory = new grpcWeb.MethodDescriptor(
    '/chat_package.ChatService/GetHistory',
    grpcWeb.MethodType.SERVER_STREAMING,
    chat_pb.HistoryRequest,
    chat_pb.Message,
    (request: chat_pb.HistoryRequest) => {
      return request.serializeBinary();
    },
    chat_pb.Message.deserializeBinary
  );

  getHistory(
    request: chat_pb.HistoryRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chat_pb.Message> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat_package.ChatService/GetHistory',
      request,
      metadata || {},
      this.methodDescriptorGetHistory);
  }

}

